### ISSUE TITLE
The bot works for a couple seconds then stops working, how do I fix?

### ISSUE THREAD

**Issue by Firestorm1051** [Da532/Innocent-bot#23]
Loading..
Ready to be innocent.
announcements has been deleted in WLR Pokémon
tournament-battles-4 has been deleted in WLR Pokémon
interactive-giveaways has been deleted in WLR Pokémon
pokecord-battles-1 has been deleted in WLR Pokémon
gaming_suggestions has been deleted in WLR Pokémon
Gaming has been deleted in WLR Pokémon
ghostflying-gym has been deleted in WLR Pokémon
elite-four-information has been deleted in WLR Pokémon
admin-chat has been deleted in WLR Pokémon
dragonground-gym has been deleted in WLR Pokémon
❓ Information ❓ has been deleted in WLR Pokémon
pokecord-trade-promotion has been deleted in WLR Pokémon
partnership-requirements has been deleted in WLR Pokémon
tournament-sign-up has been deleted in WLR Pokémon
Mudea Bot has been deleted in WLR Pokémon
Ignoring exception in command destroy:
Traceback (most recent call last):
  File "/Users/firenair/Downloads/Innocent-bot-master-2/innocent.py", line 144, in destroy
    print (f"{channel.name} has been deleted in {ctx.guild.name}")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/run.py", line 373, in write
    return self.shell.write(s, self.tags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 608, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 220, in remotecall
    return self.asyncreturn(seq)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 251, in asyncreturn
    return self.decoderesponse(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 271, in decoderesponse
    raise what
UnicodeEncodeError: 'UCS-2' codec can't encode character '\U0001f368' in position 0: Non-BMP character not supported in Tk

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/firenair/Downloads/Innocent-bot-master-2/innocent.py", line 146, in destroy
    print (f"{channel.name} has NOT been deleted in {ctx.guild.name}")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/run.py", line 373, in write
    return self.shell.write(s, self.tags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 608, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 220, in remotecall
    return self.asyncreturn(seq)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 251, in asyncreturn
    return self.decoderesponse(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/rpc.py", line 271, in decoderesponse
    raise what
UnicodeEncodeError: 'UCS-2' codec can't encode character '\U0001f368' in position 0: Non-BMP character not supported in Tk

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeEncodeError: 'UCS-2' codec can't encode character '\U0001f368' in position 0: Non-BMP character not supported in Tk

==== RESTART: /Users/firenair/Downloads/Innocent-bot-master-2/innocent.py ====
Loading..
Ready to be innocent.
Ignoring exception in command destroy:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/core.py", line 721, in invoke
    await self.prepare(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/core.py", line 678, in prepare
    await self._verify_checks(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/ext/commands/core.py", line 627, in _verify_checks
    raise CheckFailure('The check functions for command {0.qualified_name} failed.'.format(self))
discord.ext.commands.errors.CheckFailure: The check functions for command destroy failed.

**Comment by Firestorm1051** [comment]
it also sometimes says
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeEncodeError: 'UCS-2' codec can't encode character '\U0001f530' in position 0: Non-BMP character not supported in Tk

**Comment by Firestorm1051** [comment]
Actually my only problem rn is the unicode encode error, how would I fix that?
